Update build settings for 1.14.2 forge
Inventory-Tweaks/inventory-tweaks pull request #592
Opened 2019-06-15 14:22 UTC by jadar

- Update forge/MC version for 1.14.2.
- Add `mods.toml` file.

2019-06-15 15:25 UTC, Kobata requested changes

2019-06-15 15:25 UTC, Kobata commented on build.gradle
> +/*
While this stuff isn't important for locally building (in fact it shouldn't really do anything unless you've set up the configuration correctly), it is *quite* important for the CI/release build process so just disabling it isn't really a good idea.

2019-06-15 15:25 UTC, Kobata commented on src/main/resources/META-INF/mods.toml
> +# This is an example mods.toml file. It contains the data relating to the loading mods.
You probably don't need all the example text, especially stuff that's very easily outdated like the comments on what the current versions are.

The short description of each field is fine, though.

2019-06-15 15:25 UTC, Kobata commented on src/main/resources/META-INF/mods.toml
> +#logoFile="examplemod.png" #optional
This one and the next few are in the current mcmod.info file I believe.

2019-06-15 16:39 UTC, jadar commented
Let me know if there are any other changes that you would like to see. I think I addressed all your comments, so far. I clicked resolve but I'm not sure if that marks everything as "fixed". I haven't used Github's code review process much before.

2019-06-15 16:49 UTC, Kobata approved these changes

2019-06-15 16:50 UTC, merged

2019-06-19 12:48 UTC, safetypins commented
I don't have a lot of experience with Java, but I'd also like to help if I can.